/* No credentials in localStorage, URLs, cookies or console output. */
const $=id=>document.getElementById(id);
const categories={compute:'Infra',backup:'Backup',docker:'Docker',network:'Netzwerk',services:'Dienste'};
const labels={ok:'OK',warning:'Warnung',critical:'Kritisch',unknown:'Unbekannt'};
const messages={UNAUTHORIZED:'Anmeldung erforderlich. Administrator-Token prüfen.',LOGIN_RATE_LIMIT:'Zu viele Anmeldeversuche. Bitte eine Minute warten.',ORIGIN_DENIED:'Die Browseradresse stimmt nicht mit ADMIN_ORIGIN überein.',CONFIG_CONFLICT:'Ein anderer Administrator hat inzwischen gespeichert. Änderungen prüfen und die Konfiguration neu laden.',SAVE_BUSY:'Ein Speichervorgang läuft. Bitte nochmals versuchen.',CONFIG_ENTITIES:'Maximal 64 Systeme sind erlaubt.',CONFIG_TIMING:'Zeitwerte müssen ganze Sekunden von 1 bis 86400 sein.',CONFIG_STALE_WINDOW:'«Veraltet nach» muss mindestens doppelt so lang wie die Abfragepause sein.',CONFIG_PRTG_HTTPS_ORIGIN:'Eine reine HTTPS-PRTG-Adresse ohne Pfad, Zugangsdaten oder Parameter angeben.',CONFIG_ENTITY:'System prüfen: eindeutige ID, Name bis 63 UTF-8-Bytes, Kategorie und mindestens ein Sensor.',CONFIG_SENSOR_ID:'Sensor-IDs müssen positive ganze Zahlen oder leer sein und dürfen nicht mehrfach zugeordnet werden.',CONFIG_SENSOR_KEY:'Sensorschlüssel müssen eindeutig sein und aus Kleinbuchstaben, Zahlen, Bindestrich oder Unterstrich bestehen.',CONFIG_METRICS:'Kanalzuordnung prüfen: eindeutige Messwertschlüssel und nicht leere PRTG-Kanalnamen.',PRTG_TOKEN_REQUIRED:'Für eine andere PRTG-Adresse bitte auch ein neues PRTG-Token eingeben.',PRTG_TOKEN_INVALID:'Das PRTG-Token enthält ungültige Zeichen oder ist zu lang.',SAVE_FAILED:'Speichern fehlgeschlagen. Schreibrechte und freien Speicher prüfen. Bisherige Konfiguration bleibt gültig.',CONFIG_REQUEST:'Ungültige Konfiguration. Eingaben prüfen.',CONFIG_UNKNOWN_FIELD:'Unbekannte Konfigurationsfelder. Konfiguration prüfen.',CONFIG_TOO_LARGE:'Konfiguration ist zu gross.',PRTG_TEST_FAILED:'PRTG nicht erreichbar oder Zugriff abgelehnt. HTTPS-Zertifikat, API-Token, Rechte und Adresse prüfen.',FIRMWARE_DISABLED:'Firmware-Verwaltung ist serverseitig noch nicht eingerichtet.',VERSION_CONFLICT:'Diese Versionsnummer ist bereits mit einem anderen Build vorhanden. Für Korrekturen derselben Version Direktkanal oder USB verwenden.',CATALOG_FULL:'Alle acht Firmware-Plätze sind belegt. Das bestehende Archiv zuerst kontrolliert administrativ bereinigen.',UPLOAD_BUSY:'Ein anderer Upload läuft. Bitte warten.',PACKAGE_REJECTED:'Paket abgelehnt oder Speicherung fehlgeschlagen. Signiertes .eagleota-Paket, Board und Speicherrechte prüfen.',TOO_LARGE:'Firmware-Paket ist zu gross.'};
let token='',revision=0,config=null,dirty=false,idleTimer,busy=false,statusTimer;
const existingIds=new Set();
function notice(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);}
function touch(){if(token){clearTimeout(idleTimer);idleTimer=setTimeout(()=>logout(true),15*60*1000);}}
for(const event of ['pointerdown','keydown'])document.addEventListener(event,touch);
function mark(){dirty=true;$('dirty').textContent='Ungespeicherte Änderungen';}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
async function api(path,{method='GET',body,binary=false}={}){
 const response=await fetch('/api/admin/'+path,{method,cache:'no-store',headers:{Authorization:'Bearer '+token,...(body!==undefined?{'Content-Type':binary?'application/octet-stream':'application/json'}:{})},body:body===undefined?undefined:binary?body:JSON.stringify(body),signal:AbortSignal.timeout(binary?120000:35000)});
 const result=await response.json();if(!response.ok)throw Error(messages[result.error]||'Anfrage fehlgeschlagen. Bitte erneut versuchen.');return result;
}
async function action(work){try{await work();}catch(e){notice(e.name==='TimeoutError'?'Zeitüberschreitung. Gespeicherten Stand neu laden und prüfen.':e.message,true);}}
function element(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function button(text,fn,danger=false){const b=element('button',text,danger?'danger':'');b.type='button';b.addEventListener('click',fn);return b;}
function field(title,value,onChange,{type='text',readOnly=false,required=true}={}){
 const label=element('label',title),input=element('input');input.type=type;input.value=value??'';input.readOnly=readOnly;input.required=required;
 input.addEventListener('input',()=>{onChange(type==='number'?(input.value===''?null:Number(input.value)):input.value);mark();});label.append(input);return label;
}
function select(title,value,options,onChange){const label=element('label',title),input=element('select');for(const [v,t] of Object.entries(options)){const option=element('option',t);option.value=v;input.append(option);}input.value=value;input.addEventListener('change',()=>{onChange(input.value);mark();});label.append(input);return label;}
// Keep metric rows as an array in the editor so duplicate keys cannot silently overwrite values.
function toEditor(value){const c=structuredClone(value);for(const e of c.entities)for(const s of e.sensors)s.metrics=Object.entries(s.metrics).map(([key,channel])=>({key,channel}));return c;}
function toConfig(){const c=structuredClone(config);for(const e of c.entities)for(const s of e.sensors){const metrics=Object.create(null);for(const m of s.metrics){if(Object.hasOwn(metrics,m.key))throw Error('Messwertschlüssel dürfen pro Sensor nur einmal vorkommen.');metrics[m.key]=m.channel;}s.metrics=metrics;}return c;}
function renderEntities(){
 const container=$('entities');container.replaceChildren();if(!config.entities.length)container.append(element('p','Keine Systeme eingerichtet. Das Display zeigt keine aktiven Kategorien.','empty'));
 config.entities.forEach((entity,index)=>{
  const card=element('article',undefined,'card'),head=element('div',undefined,'section-head');
  head.append(element('h3',entity.label||'Neues System'),button('System entfernen',()=>{if(confirm('System «'+(entity.label||entity.id)+'» entfernen? Die Änderung wird erst mit «Speichern» übernommen.')){config.entities.splice(index,1);mark();renderEntities();}},true));card.append(head);
  const fields=element('div',undefined,'fields');fields.append(field('Interne ID',entity.id,v=>entity.id=v,{readOnly:existingIds.has(entity.id)}),field('Anzeigename',entity.label,v=>entity.label=v),select('Bereich',entity.category,categories,v=>entity.category=v));
  const active=element('label','Auf dem Display anzeigen'),check=element('input');check.type='checkbox';check.checked=entity.enabled!==false;check.addEventListener('change',()=>{entity.enabled=check.checked;mark();});active.prepend(check);fields.append(active);card.append(fields);
  entity.sensors.forEach((sensor,sensorIndex)=>{
   const block=element('div',undefined,'sensor'),row=element('div',undefined,'fields');row.append(field('Sensorschlüssel',sensor.key,v=>sensor.key=v),field('PRTG-Sensor-ID',sensor.id,v=>sensor.id=v,{type:'number',required:false}));block.append(row);
   block.append(element('p','Leer gelassene Sensor-IDs bleiben «unbekannt». Kanalnamen müssen exakt mit PRTG übereinstimmen.','muted'));
   for(const [metricIndex,metric] of sensor.metrics.entries()){
    const line=element('div',undefined,'metric');line.append(field('Messwertschlüssel',metric.key,v=>metric.key=v),field('PRTG-Kanalname',metric.channel,v=>metric.channel=v),button('Kanal entfernen',()=>{sensor.metrics.splice(metricIndex,1);mark();renderEntities();},true));block.append(line);
   }
   const actions=element('div',undefined,'actions');actions.append(button('Kanal hinzufügen',()=>{sensor.metrics.push({key:'',channel:''});mark();renderEntities();}),button('Sensor entfernen',()=>{if(confirm('Sensor und seine Kanalzuordnungen entfernen?')){entity.sensors.splice(sensorIndex,1);mark();renderEntities();}},true));block.append(actions);card.append(block);
  });
  card.append(button('Sensor hinzufügen',()=>{entity.sensors.push({key:'sensor'+(entity.sensors.length+1),id:null,metrics:[]});mark();renderEntities();}));container.append(card);
 });
}
function renderConfig(view){
 revision=view.revision;existingIds.clear();for(const e of view.config.entities)existingIds.add(e.id);config=toEditor(view.config);dirty=false;
 $('revision').textContent='Gespeicherte Revision '+revision;$('dirty').textContent='Keine offenen Änderungen';$('prtgUrl').value=config.prtg_url;$('poll').value=config.poll_seconds;$('stale').value=config.stale_seconds;$('timeout').value=config.request_timeout_seconds;$('prtgToken').value='';$('tokenState').textContent=view.hasPrtgToken?'PRTG-Token ist hinterlegt. Es wird nicht an den Browser zurückgegeben.':'Noch kein PRTG-Token hinterlegt.';renderEntities();
}
for(const [id,key] of [['prtgUrl','prtg_url'],['poll','poll_seconds'],['stale','stale_seconds'],['timeout','request_timeout_seconds']])$(id).addEventListener('input',()=>{config[key]=id==='prtgUrl'?$(id).value:Number($(id).value);mark();});
$('prtgToken').addEventListener('input',mark);
$('addSystem').addEventListener('click',()=>{let id='system'+(config.entities.length+1);while(config.entities.some(e=>e.id===id))id+='x';config.entities.push({id,label:'Neues System',category:'backup',enabled:true,sensors:[{key:'health',id:null,metrics:[]}]});mark();renderEntities();});
async function refresh(){
 const result=await api('status');if(!token)return;
 const health=result.health;const live=health.mode!=='demo';$('mode').textContent=live?'LIVE · Zustände aus der konfigurierten Datenquelle':'DEMO · Ausschliesslich synthetische Daten';
 $('summary').replaceChildren(element('strong','Gesamt: '+(labels[health.overall]||'Unbekannt')),element('strong','Letzte Daten: '+(health.updated_at?new Date(health.updated_at).toLocaleString('de-CH'):'noch keine')));
 const container=$('systemsStatus');container.replaceChildren();
 for(const [key,category] of Object.entries(health.categories))for(const e of category.entities){const card=element('article',undefined,'status-card '+(Object.hasOwn(labels,e.status)?e.status:'unknown'));card.append(element('h3',e.label),element('p',(categories[key]||key)+' · '+(labels[e.status]||'Unbekannt')));for(const s of e.sensors)card.append(element('p',s.key+': '+(labels[s.status]||'Unbekannt')+(s.reason?' · '+s.reason:''),'muted'));container.append(card);}
 if(!container.children.length)container.append(element('p','Keine aktiven Systeme. Unter «Systeme / PRTG» hinzufügen oder aktivieren.','empty'));
 $('versions').replaceChildren();$('upload').disabled=!result.firmwareEnabled||busy;
 $('firmwareState').textContent=!result.firmwareEnabled?'Firmware-Speicher ist serverseitig nicht eingerichtet.':result.firmwareError?'Firmware-Archiv konnte nicht geprüft werden. Server-Speicher und Protokoll prüfen.':result.versions.length?result.versions.length+' von 8 Versionen bereitgestellt.':'Noch keine Firmware bereitgestellt.';
 for(const [index,v] of result.versions.entries()){const card=element('article',undefined,'status-card');card.append(element('h3',v.version+(index===0?' · Neueste':'')),element('p',(v.size/1024/1024).toFixed(2)+' MiB · Signatur und Board geprüft'),element('p','SHA256: '+v.sha256,'hash'));$('versions').append(card);}
}
$('loginForm').addEventListener('submit',e=>{e.preventDefault();action(async()=>{token=$('adminToken').value;try{const view=await api('config');renderConfig(view);await refresh();$('adminToken').value='';$('login').hidden=true;$('app').hidden=false;$('logout').hidden=false;notice('Angemeldet.');touch();clearInterval(statusTimer);statusTimer=setInterval(()=>{if(token)action(refresh);},15000);}catch(error){token='';throw error;}});});
function logout(expired=false){if(busy){if(expired)touch();return;}if(!expired&&dirty&&!confirm('Ungespeicherte Änderungen verwerfen und abmelden?'))return;token='';config=null;dirty=false;clearTimeout(idleTimer);clearInterval(statusTimer);$('configForm').reset();$('entities').replaceChildren();$('systemsStatus').replaceChildren();$('versions').replaceChildren();$('summary').replaceChildren();$('app').hidden=true;$('logout').hidden=true;$('login').hidden=false;notice(expired?'Wegen Inaktivität abgemeldet. Ungespeicherte Änderungen wurden verworfen.':'Abgemeldet.');}
$('logout').addEventListener('click',()=>logout());
for(const button of document.querySelectorAll('[data-tab]'))button.addEventListener('click',()=>{for(const b of document.querySelectorAll('[data-tab]')){b.setAttribute('aria-selected',String(b===button));$(b.dataset.tab).hidden=b!==button;}});
$('refresh').addEventListener('click',()=>action(refresh));
$('discard').addEventListener('click',()=>action(async()=>{if(!dirty||confirm('Alle ungespeicherten Änderungen verwerfen?')){renderConfig(await api('config'));notice('Gespeicherte Konfiguration geladen.');}}));
$('configForm').addEventListener('submit',e=>{e.preventDefault();action(async()=>{if(busy)return;busy=true;$('configFields').disabled=true;$('logout').disabled=true;$('save').disabled=true;try{const view=await api('config',{method:'PUT',body:{revision,config:toConfig(),prtgToken:$('prtgToken').value}});renderConfig(view);notice('Gespeichert und übernommen. Neue Messwerte werden abgefragt; bis dahin ist der Zustand unbekannt.');await refresh();}finally{busy=false;$('configFields').disabled=false;$('logout').disabled=false;$('save').disabled=false;}});});
$('prtgTest').addEventListener('click',()=>action(async()=>{$('prtgTest').disabled=true;try{notice('Gespeicherte PRTG-Verbindung wird geprüft …');notice((await api('prtg-test',{method:'POST'})).message);}finally{$('prtgTest').disabled=false;}}));
$('firmwareForm').addEventListener('submit',e=>{e.preventDefault();action(async()=>{if(busy)return;const file=$('firmwareFile').files[0];if(!file||!file.name.endsWith('.eagleota')||file.size>0x400000+8196)throw Error('Bitte ein signiertes .eagleota-Paket bis maximal 4 MiB plus Metadaten auswählen.');busy=true;$('logout').disabled=true;$('upload').disabled=true;$('uploadState').textContent='Paket wird übertragen, geprüft und gespeichert …';try{const result=await api('firmware',{method:'PUT',body:file,binary:true});$('uploadState').textContent='Version '+result.version+(result.existing?' war bereits vorhanden.':' ist bereitgestellt. Am Display «Versionen prüfen» wählen.');$('firmwareForm').reset();}catch(error){$('uploadState').textContent='Nicht bereitgestellt.';throw error;}finally{busy=false;$('logout').disabled=false;await refresh();}});});
